Bubble sort feature
mohapakram/Bubble-Sort pull request #1
Opened 2020-08-13 14:02 UTC by GraceOyiza

- Add a bubble_sort method.
- Add a bubble_sort_by method.

2020-08-13 14:11 UTC, GraceOyiza commented
- Linters error fixed

2020-08-13 23:06 UTC, krys2fa requested changes
## Awesome work @GraceOyiza and @mohapakram 👏 
Your project displays good use of Github Flow workflow and has descriptive commit messages. 💪 

### Status: Changes Required ♻️ 
It is important that your repo is as professional as possible. As a result, kindly make the changes in your README file as stated below

Please request for another review after implementing the changes.

Happy Coding 🖥️  😃 

###### You can contact me on slack (Chris Amanor) for any clarification.

2020-08-13 23:06 UTC, krys2fa commented on README.md
>  # Project Name
- [ ] Please replace this with the actual name of the project or remove it completely.

2020-08-13 23:06 UTC, krys2fa commented on README.md
> +One paragraph statement about the project.
- [ ] Please replace this with the actual statement on the project or remove it completely.

2020-08-13 23:06 UTC, krys2fa commented on README.md
>  Additional description about the project and its features.
- [ ] Please replace this with the actual description or remove it completely.

2020-08-15 07:18 UTC, addod19 approved these changes
## Status: Approved :trophy: :balloon: 

Hi @GraceOyiza and @mohapakram, great job fixing the comments made by the previous TSE :+1: The README is fixed with the necessary text. I hereby approve of the project, congratulations :fireworks: 

Go ahead and merge to master :slightly_smiling_face: 
_Happy coding_ :woman_technologist: :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2020-08-16 12:32 UTC, merged